version: '3.8'

services:
  postgres-caf:
    image: postgres:15
    container_name: postgres-caf-dumps
    environment:
      POSTGRES_DB: caf_analysis
      POSTGRES_USER: caf_user
      POSTGRES_PASSWORD: caf_password123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5433:5432"  # Usar porta diferente para evitar conflito
    volumes:
      - postgres_caf_data:/var/lib/postgresql/data
      - ./dumps:/dumps:ro  # Mount dos dumps como read-only
      - ./postgres-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - caf-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U caf_user -d caf_analysis"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Interface web para gerenciar PostgreSQL
  pgadmin-caf:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-caf
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@caf.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8081:80"
    volumes:
      - pgadmin_caf_data:/var/lib/pgadmin
    networks:
      - caf-network
    depends_on:
      postgres-caf:
        condition: service_healthy

volumes:
  postgres_caf_data:
  pgadmin_caf_data:

networks:
  caf-network:
    driver: bridge
